#!/usr/bin/env python3
"""Generate the Julian and hybrid calendar vectors from `convertdate`.

design.md section 12 names *Calendrical Calculations*' sample-date tables and
the `convertdate` package as the oracles for the calendars beyond Gregorian.
`convertdate` implements Reingold and Dershowitz's algorithms directly, in
code this library did not write, which is what makes it an oracle rather than
a second opinion from the same person.

It is not installed on a Debian system and PEP 668 will not let pip put it in
the system interpreter, so:

    python3 -m venv /tmp/chron-oracle
    /tmp/chron-oracle/bin/pip install convertdate
    /tmp/chron-oracle/bin/python tools/oracle/calendars.py

The vectors it writes are committed, so `make test` needs none of that.

Two files come out:

``julian.vec``
    Every 691st day from year 1 to year 9999 - a stride coprime with 4, 7 and
    every month length, so the sample walks through leap years, weekdays and
    month boundaries rather than around them - plus every day of the four
    years around each century boundary where the Julian and Gregorian leap
    rules disagree, which is where a reader that confused the two shows it.

``hybrid.vec``
    Every day from a fortnight before to a fortnight after each of the three
    cut-overs this library names, labelled with which calendar governs it and
    whether the label exists at all. The deleted days are the point.

Usage:  tools/oracle/calendars.py [--out tests/data/vectors/calendar]

Copyright 2026 by Corey Pennycuff
"""

import argparse
import pathlib
import sys

try:
    from convertdate import gregorian, julian
except ImportError:  # pragma: no cover - the message is the whole point
    sys.stderr.write(
        "calendars.py: convertdate is not installed.\n"
        "  python3 -m venv /tmp/chron-oracle\n"
        "  /tmp/chron-oracle/bin/pip install convertdate\n"
        "  /tmp/chron-oracle/bin/python tools/oracle/calendars.py\n"
        "The oracle is the authority here; without it this generator is not\n"
        "weaker, it is absent, and saying so beats writing vectors by hand.\n")
    sys.exit(1)

# 1970-01-01T00:00 UTC as a Julian Date. convertdate works in Julian Days,
# which start at noon, so every conversion here lands on a .5 and the integer
# epoch day is the difference.
JD_UNIX_EPOCH = 2440587.5

STRIDE = 691

CUTOVERS = (
    ("rome", 1582, 10, 15),
    ("britain", 1752, 9, 14),
    ("russia", 1918, 2, 14),
)


def epoch_day_of_gregorian(year, month, day):
    return int(gregorian.to_jd(year, month, day) - JD_UNIX_EPOCH)


def epoch_day_of_julian(year, month, day):
    return int(julian.to_jd(year, month, day) - JD_UNIX_EPOCH)


def julian_rows():
    """Julian labels for a stride of days, and for the century boundaries."""
    days = set()

    first = epoch_day_of_gregorian(1, 1, 1)
    last = epoch_day_of_gregorian(9999, 12, 31)
    days.update(range(first, last + 1, STRIDE))

    # Every day of the four years around each century, where the two leap
    # rules disagree - 1700, 1800 and 1900 are Julian leap years and Gregorian
    # common ones, and a reader that mixed them up is wrong by a day from
    # there on.
    for century in range(100, 2101, 100):
        start = epoch_day_of_gregorian(century - 1, 1, 1)
        end = epoch_day_of_gregorian(century + 2, 12, 31)
        days.update(range(start, end + 1))

    for day in sorted(days):
        year, month, mday = julian.from_jd(day + JD_UNIX_EPOCH)
        yield "%d\t%d-%02d-%02d" % (day, year, month, mday)


def hybrid_rows():
    """Which calendar labels each day around a cut-over, and what it says."""
    for name, year, month, day in CUTOVERS:
        cutover = epoch_day_of_gregorian(year, month, day)
        for probe in range(cutover - 20, cutover + 20):
            if probe < cutover:
                y, m, d = julian.from_jd(probe + JD_UNIX_EPOCH)
                which = "julian"
            else:
                y, m, d = gregorian.from_jd(probe + JD_UNIX_EPOCH)
                which = "gregory"
            yield "%s\t%d\t%s\t%d-%02d-%02d" % (name, probe, which, y, m, d)


HEADERS = {
    "julian.vec":
        "# epoch_day <TAB> julian_label\n"
        "# Generated by tools/oracle/calendars.py from the convertdate\n"
        "# package, which implements Reingold and Dershowitz's algorithms.\n"
        "# Every %dth day of years 1-9999, plus every day of the four years\n"
        "# around each century boundary.\n" % STRIDE,
    "hybrid.vec":
        "# cutover <TAB> epoch_day <TAB> governing_calendar <TAB> label\n"
        "# Generated by tools/oracle/calendars.py from convertdate.\n"
        "# Twenty days either side of each of the three cut-overs.\n",
}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="tests/data/vectors/calendar")
    args = parser.parse_args()

    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    for name, rows in (("julian.vec", julian_rows()),
                       ("hybrid.vec", hybrid_rows())):
        path = out / name
        count = 0
        with path.open("w") as handle:
            handle.write(HEADERS[name])
            for row in rows:
                handle.write(row + "\n")
                count += 1
        print("%s: %d rows" % (path, count))
    return 0


if __name__ == "__main__":
    sys.exit(main())
