#!/usr/bin/env python3
"""Turn the JSON-Schema-Test-Suite's optional format vectors into ours.

The suite is the oracle for what `format: date-time`, `date`, `time` and
`duration` accept.  It is a corpus this library did not write, maintained by
the people who specify the keyword, and it is what every other implementation
is measured against - which is exactly the property design.md section 12 asks
of an oracle, and exactly what a corpus grown from one's own fixes lacks.

Cases whose `data` is not a string are dropped: "all string formats ignore
integers" is a statement about a JSON Schema engine's dispatch, not about a
grammar, and it belongs to `text` rather than here.  How many were dropped is
printed, so the drop is visible rather than assumed.

The output is one file per format under `tests/data/vectors/parse`, with one
case per line and three tab-separated fields:

    valid|invalid <TAB> escaped-text <TAB> description

The text is escaped so that a vector file is a line-oriented ASCII file a
human can read: a printable ASCII byte stands for itself, except backslash and
tab, and everything else - the suite's newlines, NULs and Bengali digits -
becomes ``\\xHH``.  ``tests/conformance/test_jsonschema_format.cpp`` reverses
it.

Usage:  tools/oracle/jsonschema_format.py --suite <dir> [--out <dir>]

Copyright 2026 by Corey Pennycuff
"""

import argparse
import json
import pathlib
import sys

FORMATS = ("date-time", "date", "time", "duration")

SUITE_PATH = "tests/draft2020-12/optional/format/%s.json"


def escape(text):
    out = []
    for byte in text.encode("utf-8"):
        if byte == 0x5C:
            out.append("\\\\")
        elif 0x20 <= byte < 0x7F:
            out.append(chr(byte))
        else:
            out.append("\\x%02x" % byte)
    return "".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--suite", required=True,
                        help="the fetched JSON-Schema-Test-Suite tree")
    parser.add_argument("--out", default="tests/data/vectors/parse",
                        help="where to write the vector files")
    args = parser.parse_args()

    suite = pathlib.Path(args.suite)
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    commit = suite.name
    status = 0

    for name in FORMATS:
        source = suite / (SUITE_PATH % name)
        if not source.is_file():
            sys.stderr.write("missing %s; run tools/corpus/fetch.sh\n" % source)
            status = 1
            continue

        groups = json.loads(source.read_text())
        rows = []
        skipped = 0
        for group in groups:
            for case in group["tests"]:
                data = case["data"]
                if not isinstance(data, str):
                    skipped += 1
                    continue
                rows.append("%s\t%s\t%s" % (
                    "valid" if case["valid"] else "invalid",
                    escape(data),
                    case["description"].replace("\t", " "),
                ))

        path = out / ("jsonschema_%s.vec" % name.replace("-", "_"))
        with path.open("w") as handle:
            handle.write(
                "# JSON Schema `format: %s`, from the JSON-Schema-Test-Suite\n"
                "# at %s, file %s.\n"
                "# Generated by tools/oracle/jsonschema_format.py; do not "
                "edit.\n"
                "# valid|invalid <TAB> escaped-text <TAB> description\n"
                % (name, commit, SUITE_PATH % name))
            for row in rows:
                handle.write(row + "\n")
        print("%s: %d cases (%d non-string cases dropped)"
              % (path, len(rows), skipped))

    return status


if __name__ == "__main__":
    sys.exit(main())
