#!/usr/bin/env python3
"""Vectors for leap.h, from the tzdb's own `leapseconds` file.

design.md section 12: every vector comes from outside software, never from
memory. The built-in table is generated from `leap-seconds.list`, so checking
it against that same file would prove only that the generator can read its own
output. `/usr/share/zoneinfo/leapseconds` is the *other* file the tzdb ships:
the same facts, restated in zic's input syntax by zic's own maintainers, with
one leap second per line and the sign spelled out. Agreeing with it is
evidence; agreeing with leap-seconds.list is not.

It also states each leap second the way a person does - "a second was added at
the end of 30 June 1972" - which is exactly the question
gchron_leap_is_leap_day() answers, so no arithmetic of ours sits between the
oracle and the assertion.

Writes tests/data/vectors/leap/leapseconds.vec:

    # <tzdb leapseconds file>
    expires <unix seconds>
    leap <yyyy-mm-dd> <+|-> <cumulative TAI-UTC after it>

Usage:
    tools/oracle/leapseconds.py [source] [-o output]
"""

import argparse
import datetime
import os
import pathlib
import re
import sys

MONTHS = {m: i for i, m in enumerate(
    ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
     "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"], start=1)}

DEFAULT_SOURCES = [
    os.path.join(os.environ["TZDIR"], "leapseconds")
    if os.environ.get("TZDIR") else None,
    "/usr/share/zoneinfo/leapseconds",
]

# The offset TAI-UTC held when UTC became a stepped scale, before any of the
# leap seconds this file lists. It is not in this file, which is the point:
# the file lists *leap seconds*, and the initial offset is not one. Stated
# here rather than read from leap-seconds.list so the two stay independent.
# Reference: ITU-R TF.460-6, and BIPM Circular T.
INITIAL_TAI_MINUS_UTC = 10


def parse(text):
    leaps = []
    expires = None
    for line in text.splitlines():
        if line.startswith("Leap"):
            parts = line.split()
            # Leap  YEAR MON DAY  HH:MM:SS  CORR  R/S
            year, month, day = int(parts[1]), MONTHS[parts[2]], int(parts[3])
            sign = parts[5]
            if sign not in ("+", "-"):
                raise SystemExit("unexpected correction %r" % sign)
            leaps.append((datetime.date(year, month, day), sign))
        else:
            found = re.match(r"#expires\s+(\d+)", line)
            if found:
                expires = int(found.group(1))

    if not leaps:
        raise SystemExit("no Leap lines found; is this a leapseconds file?")
    if expires is None:
        raise SystemExit("no #expires line found")
    if leaps != sorted(leaps):
        raise SystemExit("Leap lines are not in date order")
    return leaps, expires


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", nargs="?", default=None)
    parser.add_argument("-o", "--output",
                        default="tests/data/vectors/leap/leapseconds.vec")
    args = parser.parse_args()

    source = args.source
    if source is None:
        for candidate in DEFAULT_SOURCES:
            if candidate and os.path.exists(candidate):
                source = candidate
                break
    if source is None or not os.path.exists(source):
        raise SystemExit(
            "no tzdb 'leapseconds' file found (looked in %s). It ships with\n"
            "tzdata; on Debian, apt-get install tzdata."
            % ", ".join(c for c in DEFAULT_SOURCES if c))

    leaps, expires = parse(pathlib.Path(source).read_text())

    lines = ["# generated by tools/oracle/leapseconds.py from %s" % source,
             "# one line per leap second, with TAI-UTC after it",
             "expires %d" % expires]
    offset = INITIAL_TAI_MINUS_UTC
    for date, sign in leaps:
        offset += 1 if sign == "+" else -1
        lines.append("leap %s %s %d" % (date.isoformat(), sign, offset))

    output = pathlib.Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n")

    print("%s: %d leap seconds, TAI-UTC ends at %d, expires %d"
          % (args.output, len(leaps), offset, expires))
    return 0


if __name__ == "__main__":
    sys.exit(main())
