#!/usr/bin/env python3
"""Generate the Gregorian calendar vectors from Python's own calendar.

Python's ``datetime.date`` implements the proleptic Gregorian calendar over
years 1..9999 in code this library did not write, which is the whole point:
design.md section 12 says every vector comes from an oracle, and a corpus
grown from one's own fixes measures the fixes.

Two files come out, and they pin different things:

``gregorian_years.vec``
    One row per year 1..9999: the epoch day of 1 January, its ISO weekday,
    the length of the year, and the twelve month lengths.  The month lengths
    matter because the exhaustive sweep in ``tests/unit/test_civil.cpp``
    proves the labelling steps one day at a time and round-trips, which it
    would still do if August were thirty days and September thirty-one.  This
    is what says which month is which.

``gregorian_dates.vec``
    Every 997th day from 0001-01-01 to 9999-12-31 - a stride coprime with 7,
    with 146097, and with every month length, so the sample walks through
    weekdays, leap rules and month boundaries rather than around them.  Each
    row carries the ISO week date and the ordinal day as well, which pins
    ``gchron_date_to_iso_week`` and ``gchron_date_day_of_year`` against
    ``date.isocalendar()`` and ``date.timetuple().tm_yday``.

Usage:  tools/oracle/ordinal.py [--out tests/data/vectors/calendar]

Copyright 2026 by Corey Pennycuff
"""

import argparse
import datetime
import pathlib
import sys

# Python counts from 0001-01-01 as ordinal 1 (Rata Die); this library counts
# from 1970-01-01 as epoch day 0.  One constant relates them, and
# tests/unit/test_civil.cpp asserts the library agrees about it.
RD_OFFSET = 719163

STRIDE = 997


def years_rows():
    for year in range(1, 10000):
        jan1 = datetime.date(year, 1, 1)
        next_jan1 = datetime.date(year + 1, 1, 1) if year < 9999 else None
        if next_jan1 is not None:
            days_in_year = (next_jan1 - jan1).days
        else:
            days_in_year = (datetime.date(9999, 12, 31) - jan1).days + 1
        lengths = []
        for month in range(1, 13):
            start = datetime.date(year, month, 1)
            if month == 12:
                end = datetime.date(year, 12, 31)
                lengths.append((end - start).days + 1)
            else:
                end = datetime.date(year, month + 1, 1)
                lengths.append((end - start).days)
        yield "%d %d %d %d %s" % (
            year,
            jan1.toordinal() - RD_OFFSET,
            jan1.isoweekday(),
            days_in_year,
            ",".join(str(n) for n in lengths),
        )


def dates_rows():
    first = datetime.date(1, 1, 1).toordinal()
    last = datetime.date(9999, 12, 31).toordinal()
    for ordinal in range(first, last + 1, STRIDE):
        d = datetime.date.fromordinal(ordinal)
        iso_year, iso_week, iso_day = d.isocalendar()
        yield "%04d-%02d-%02d %d %d %d %d-W%02d-%d %d" % (
            d.year,
            d.month,
            d.day,
            ordinal - RD_OFFSET,
            d.isoweekday(),
            d.timetuple().tm_yday,
            iso_year,
            iso_week,
            iso_day,
            ordinal,
        )


HEADERS = {
    "gregorian_years.vec":
        "# year epoch_day_of_jan1 iso_weekday_of_jan1 days_in_year "
        "month_lengths\n"
        "# Generated by tools/oracle/ordinal.py from Python "
        "%s's datetime.date.\n" % ".".join(str(n) for n in sys.version_info[:3]),
    "gregorian_dates.vec":
        "# yyyy-mm-dd epoch_day iso_weekday day_of_year iso_week_date "
        "rata_die\n"
        "# Every %dth day from 0001-01-01. Generated by "
        "tools/oracle/ordinal.py\n"
        "# from Python %s's datetime.date.\n"
        % (STRIDE, ".".join(str(n) for n in sys.version_info[:3])),
}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="tests/data/vectors/calendar",
                        help="where to write the vector files")
    args = parser.parse_args()

    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    for name, rows in (("gregorian_years.vec", years_rows()),
                       ("gregorian_dates.vec", dates_rows())):
        path = out / name
        with path.open("w") as handle:
            handle.write(HEADERS[name])
            count = 0
            for row in rows:
                handle.write(row + "\n")
                count += 1
        print("%s: %d rows" % (path, count))


if __name__ == "__main__":
    main()
