#!/usr/bin/env python3
"""Generate src/zone/windows_zones.c from CLDR's windowsZones.xml.

Windows does not name its time zones the way the rest of the world does. It
says "Pacific Standard Time" where the tzdb says `America/Los_Angeles`, and
`GetDynamicTimeZoneInformation()` returns the former. CLDR publishes the
mapping between them, and this turns it into a table.

**The XML is not committed and not fetched by the build.** It is somebody
else's data, it is reproducible from a URL and a tag, and a copy here would be
a snapshot that quietly stops matching what Windows and CLDR agree on - the
same reasoning tools/corpus/fetch.sh gives for the JSON Schema suite. Get it
with:

    tools/tzdata/fetch-cldr.sh

and then run this. Without it there is no table, and gchron_zone_id_from_windows()
is not built: design.md's rule is that what a phase cannot do is absent rather
than stubbed, and a mapping table with no rows would answer every lookup
"unknown" and look exactly like one that was asked about a zone Windows has
since added.

Usage:
    tools/tzdata/windows_zones.py [windowsZones.xml] [-o output]
"""

import argparse
import os
import pathlib
import sys
import xml.etree.ElementTree as ElementTree

DEFAULT_PATHS = [
    "third_party/cldr/windowsZones.xml",
    "/usr/share/unicode/cldr/common/supplemental/windowsZones.xml",
]


def parse(path):
    """Return [(windows_name, territory, [iana ids])], and the CLDR version."""
    tree = ElementTree.parse(path)
    root = tree.getroot()

    # CLDR records two versions on <mapTimezones>, and neither is the CLDR
    # release: `typeVersion` is the tzdata release the IANA identifiers were
    # taken from, and `otherVersion` is Microsoft's own. The <version> element
    # holds an unexpanded "$Revision$" and says nothing.
    #
    # What matters for auditing is which release of *this file* was used, so
    # the CLDR tag is read from tools/tzdata/CLDR_TAG - the same tag
    # fetch-cldr.sh downloaded by - and the tzdata version is carried beside
    # it, because a mapping generated against a years-old tzdata may name
    # zones the tzdb has since renamed.
    node = root.find(".//mapTimezones")
    type_version = node.get("typeVersion") if node is not None else None

    tag = None
    tag_file = pathlib.Path(__file__).resolve().parent / "CLDR_TAG"
    if tag_file.exists():
        tag = tag_file.read_text().strip() or None

    if tag and type_version:
        version = "%s (tzdata %s)" % (tag, type_version)
    else:
        version = tag or type_version

    rows = []
    for zone in root.findall(".//mapZone"):
        other = zone.get("other")
        territory = zone.get("territory")
        ids = (zone.get("type") or "").split()
        if not other or not ids:
            continue
        rows.append((other, territory or "001", ids))

    if not rows:
        raise SystemExit("%s contains no <mapZone> elements" % path)
    return rows, version


def render(rows, version, source):
    # The territory "001" row is the default for a Windows zone name, and the
    # first identifier on it is the one CLDR calls primary. That is what a
    # lookup by name alone should answer, so those rows go first and the
    # lookup stops at the first match for a name.
    primary = {}
    for other, territory, ids in rows:
        if territory == "001" and other not in primary:
            primary[other] = ids[0]

    missing = sorted({other for other, _, _ in rows} - set(primary))
    if missing:
        raise SystemExit(
            "no territory=\"001\" row for: %s\n"
            "Every Windows zone name must have a default, or a lookup by name "
            "alone has no answer to give." % ", ".join(missing))

    entries = "\n".join(
        '  { "%s", "%s" },' % (name, primary[name])
        for name in sorted(primary))

    return TEMPLATE % {
        "source": source,
        "version": version or "unknown",
        "count": len(primary),
        "entries": entries,
    }


TEMPLATE = '''/**
 * @file
 *
 * Windows time-zone names, mapped to IANA identifiers.
 *
 * GENERATED by tools/tzdata/windows_zones.py from %(source)s
 * (CLDR %(version)s). Do not edit: regenerate it.
 *
 * %(count)d names. Windows reports "Pacific Standard Time" where the tzdb
 * says `America/Los_Angeles`, and GetDynamicTimeZoneInformation() is the
 * only way to ask a Windows machine what zone it is set to - so without this
 * table gchron_zonedb_local() has nothing to return there (design.md
 * section 6.5).
 *
 * Only CLDR's default territory ("001") rows are here. A Windows zone name
 * covers several IANA zones in general - "Eastern Standard Time" is Toronto
 * as well as New York - and they agree on offsets and rules, which is what
 * makes one of them a usable answer. A caller who needs the territory
 * distinction wants a locale database, not this.
 *
 * Copyright 2026 by Corey Pennycuff
 */

#include <ghoti.io/chron/macros.h>
#include <stddef.h>
#include <string.h>

#include "zone_internal.h"

/** The CLDR release this was generated from. */
static const char CLDR_VERSION[] = "%(version)s";

/** Sorted by the Windows name, so that a lookup is a binary search. */
static const GCHRON_WindowsZone ZONES[] = {
%(entries)s
};

const char * gchron_windows_zones_version(void) {
  return CLDR_VERSION;
}

size_t gchron_windows_zones_count(void) {
  return sizeof(ZONES) / sizeof(ZONES[0]);
}

const GCHRON_WindowsZone * gchron_windows_zones_at(size_t index) {
  if (index >= gchron_windows_zones_count()) {
    return NULL;
  }
  return &ZONES[index];
}

const char * gchron_windows_zones_lookup(const char * windows_name) {
  size_t low = 0;
  size_t high = gchron_windows_zones_count();

  if (windows_name == NULL) {
    return NULL;
  }
  while (low < high) {
    size_t mid = low + (high - low) / 2;
    int order = strcmp(windows_name, ZONES[mid].windows_name);
    if (order == 0) {
      return ZONES[mid].iana_id;
    }
    if (order < 0) {
      high = mid;
    }
    else {
      low = mid + 1;
    }
  }
  return NULL;
}
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", nargs="?", default=None)
    parser.add_argument("-o", "--output", default="src/zone/windows_zones.c")
    args = parser.parse_args()

    source = args.source
    if source is None:
        for candidate in DEFAULT_PATHS:
            if os.path.exists(candidate):
                source = candidate
                break
    if source is None or not os.path.exists(source):
        raise SystemExit(
            "no windowsZones.xml found (looked in %s).\n"
            "Fetch it with tools/tzdata/fetch-cldr.sh, or pass a path."
            % ", ".join(DEFAULT_PATHS))

    rows, version = parse(source)
    if version is None:
        raise SystemExit(
            "%s carries no version, and tools/tzdata/CLDR_TAG is missing or "
            "empty.\nThe mapping must be able to say which release it came "
            "from - gchron_zone_windows_mapping_version() reports it, and a "
            "name this table does not carry is only explicable against a "
            "release." % source)
    output = pathlib.Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(rows, version, source))

    print("%s: CLDR %s, %d Windows zone names"
          % (args.output, version,
             len({other for other, t, _ in rows if t == "001"})))
    return 0


if __name__ == "__main__":
    sys.exit(main())
