/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Chron.
 *
 * Ghoti.io Chron is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Chron is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file
 *
 * The leap-second table compiled into this library.
 *
 * GENERATED by tools/leap/embed.py from /usr/share/zoneinfo/leap-seconds.list
 * (last updated 2026-07-06). Do not edit: regenerate it.
 *
 * This table **expires on 2027-06-28**, which is the expiry the source
 * file carried. Past that date every conversion through it reports
 * GCHRON_ERR_EXPIRED rather than assuming no further leap second was issued.
 * A binary built years ago must not answer confidently about a year it could
 * not have known about (design.md section 5.1 item 3).
 */

#include <ghoti.io/chron/leap.h>
#include <ghoti.io/chron/macros.h>

#include "leap_internal.h"

/** Every leap second issued as of the source file above. */
static const GCHRON_LeapEntry BUILTIN_ENTRIES[] = {
  { { INT64_C(63072000), 0 }, 10, false },  /* 1972-01-01  UTC becomes a stepped scale */
  { { INT64_C(78796800), 0 }, 11, false },  /* 1972-07-01  +1s at the end of the previous day */
  { { INT64_C(94694400), 0 }, 12, false },  /* 1973-01-01  +1s at the end of the previous day */
  { { INT64_C(126230400), 0 }, 13, false },  /* 1974-01-01  +1s at the end of the previous day */
  { { INT64_C(157766400), 0 }, 14, false },  /* 1975-01-01  +1s at the end of the previous day */
  { { INT64_C(189302400), 0 }, 15, false },  /* 1976-01-01  +1s at the end of the previous day */
  { { INT64_C(220924800), 0 }, 16, false },  /* 1977-01-01  +1s at the end of the previous day */
  { { INT64_C(252460800), 0 }, 17, false },  /* 1978-01-01  +1s at the end of the previous day */
  { { INT64_C(283996800), 0 }, 18, false },  /* 1979-01-01  +1s at the end of the previous day */
  { { INT64_C(315532800), 0 }, 19, false },  /* 1980-01-01  +1s at the end of the previous day */
  { { INT64_C(362793600), 0 }, 20, false },  /* 1981-07-01  +1s at the end of the previous day */
  { { INT64_C(394329600), 0 }, 21, false },  /* 1982-07-01  +1s at the end of the previous day */
  { { INT64_C(425865600), 0 }, 22, false },  /* 1983-07-01  +1s at the end of the previous day */
  { { INT64_C(489024000), 0 }, 23, false },  /* 1985-07-01  +1s at the end of the previous day */
  { { INT64_C(567993600), 0 }, 24, false },  /* 1988-01-01  +1s at the end of the previous day */
  { { INT64_C(631152000), 0 }, 25, false },  /* 1990-01-01  +1s at the end of the previous day */
  { { INT64_C(662688000), 0 }, 26, false },  /* 1991-01-01  +1s at the end of the previous day */
  { { INT64_C(709948800), 0 }, 27, false },  /* 1992-07-01  +1s at the end of the previous day */
  { { INT64_C(741484800), 0 }, 28, false },  /* 1993-07-01  +1s at the end of the previous day */
  { { INT64_C(773020800), 0 }, 29, false },  /* 1994-07-01  +1s at the end of the previous day */
  { { INT64_C(820454400), 0 }, 30, false },  /* 1996-01-01  +1s at the end of the previous day */
  { { INT64_C(867715200), 0 }, 31, false },  /* 1997-07-01  +1s at the end of the previous day */
  { { INT64_C(915148800), 0 }, 32, false },  /* 1999-01-01  +1s at the end of the previous day */
  { { INT64_C(1136073600), 0 }, 33, false },  /* 2006-01-01  +1s at the end of the previous day */
  { { INT64_C(1230768000), 0 }, 34, false },  /* 2009-01-01  +1s at the end of the previous day */
  { { INT64_C(1341100800), 0 }, 35, false },  /* 2012-07-01  +1s at the end of the previous day */
  { { INT64_C(1435708800), 0 }, 36, false },  /* 2015-07-01  +1s at the end of the previous day */
  { { INT64_C(1483228800), 0 }, 37, false },  /* 2017-01-01  +1s at the end of the previous day */
};

static const GCHRON_LeapTable BUILTIN_TABLE = {
  NULL,                      /* allocator: nothing here is owned */
  BUILTIN_ENTRIES,
  28,
  INT64_C(1814140800),  /* expires 2027-06-28 */
  INT64_C(1783323897),
  true
};

const GCHRON_LeapTable * gchron_leap_table_builtin(void) {
  return &BUILTIN_TABLE;
}
