#!/usr/bin/env python3
"""Generate src/leap/leap_builtin.c from a leap-seconds.list.

The built-in table is a fallback for a machine that has no copy of the file.
It is generated, never edited, and this script **fails rather than writing a
placeholder** (CONVENTIONS.md section 6): a table of zero leap seconds would
answer every conversion wrongly and look like it was working.

The expiry is copied from the source file rather than invented, so a binary
built from an old file reports GCHRON_ERR_EXPIRED instead of pretending its
knowledge is current. That is the point of design.md section 5.1 item 3.

Usage:
    tools/leap/embed.py [source] [-o output]

`source` defaults to $TZDIR/leap-seconds.list or
/usr/share/zoneinfo/leap-seconds.list.
"""

import argparse
import datetime
import os
import pathlib
import sys

NTP_TO_UNIX = 2208988800

DEFAULT_SOURCES = [
    os.path.join(os.environ["TZDIR"], "leap-seconds.list")
    if os.environ.get("TZDIR") else None,
    "/usr/share/zoneinfo/leap-seconds.list",
    "/usr/share/zoneinfo-leaps/leap-seconds.list",
]


def parse(text):
    """Return (entries, updated_ntp, expiry_ntp).

    entries is a list of (ntp, offset). The parse is deliberately strict:
    this runs at build time, where a malformed file must stop the build
    rather than silently produce a shorter table.
    """
    entries = []
    updated = None
    expiry = None

    for number, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            if line.startswith("#$"):
                updated = int(line[2:].strip())
            elif line.startswith("#@"):
                expiry = int(line[2:].strip())
            continue
        # Data: <ntp> <offset> [# comment]
        body = line.split("#", 1)[0].split()
        if len(body) < 2:
            raise SystemExit("line %d: expected an NTP time and an offset: %r"
                             % (number, raw))
        entries.append((int(body[0]), int(body[1])))

    if not entries:
        raise SystemExit("no leap-second entries in the source file")
    if expiry is None:
        raise SystemExit("the source file carries no #@ expiry line")
    if entries != sorted(entries):
        raise SystemExit("the source file's entries are not in time order")
    return entries, updated, expiry


def iso(ntp):
    """An NTP timestamp as a readable UTC date, for the generated comments."""
    moment = datetime.datetime(1970, 1, 1, tzinfo=datetime.timezone.utc) \
        + datetime.timedelta(seconds=ntp - NTP_TO_UNIX)
    return moment.strftime("%Y-%m-%d")


def render(entries, updated, expiry, source):
    rows = []
    previous = None
    for ntp, offset in entries:
        unix = ntp - NTP_TO_UNIX
        if previous is None:
            note = "UTC becomes a stepped scale"
        elif offset > previous:
            note = "+1s at the end of the previous day"
        elif offset < previous:
            note = "-1s at the end of the previous day (negative leap)"
        else:
            note = "no change"
        negative = "true" if previous is not None and offset < previous \
            else "false"
        rows.append(
            "  { { INT64_C(%d), 0 }, %d, %s },  /* %s  %s */"
            % (unix, offset, negative, iso(ntp), note))
        previous = offset

    return TEMPLATE % {
        "source": source,
        "generated_from": iso(updated) if updated else "unknown",
        "expiry_iso": iso(expiry),
        "rows": "\n".join(rows),
        "count": len(entries),
        "expiry_unix": expiry - NTP_TO_UNIX,
        "updated_unix": (updated - NTP_TO_UNIX) if updated
        else (entries[-1][0] - NTP_TO_UNIX),
    }


# Every generated source carries the same licence notice as a hand-written
# one. It is emitted here rather than added afterwards, so that regenerating
# does not quietly drop it.
LICENSE_NOTICE = """\
/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Chron.
 *
 * Ghoti.io Chron is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Chron is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
"""


TEMPLATE = LICENSE_NOTICE + "\n" + '''/**
 * @file
 *
 * The leap-second table compiled into this library.
 *
 * GENERATED by tools/leap/embed.py from %(source)s
 * (last updated %(generated_from)s). Do not edit: regenerate it.
 *
 * This table **expires on %(expiry_iso)s**, which is the expiry the source
 * file carried. Past that date every conversion through it reports
 * GCHRON_ERR_EXPIRED rather than assuming no further leap second was issued.
 * A binary built years ago must not answer confidently about a year it could
 * not have known about (design.md section 5.1 item 3).
 */

#include <ghoti.io/chron/leap.h>
#include <ghoti.io/chron/macros.h>

#include "leap_internal.h"

/** Every leap second issued as of the source file above. */
static const GCHRON_LeapEntry BUILTIN_ENTRIES[] = {
%(rows)s
};

static const GCHRON_LeapTable BUILTIN_TABLE = {
  NULL,                      /* allocator: nothing here is owned */
  BUILTIN_ENTRIES,
  %(count)d,
  INT64_C(%(expiry_unix)d),  /* expires %(expiry_iso)s */
  INT64_C(%(updated_unix)d),
  true
};

const GCHRON_LeapTable * gchron_leap_table_builtin(void) {
  return &BUILTIN_TABLE;
}
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", nargs="?", default=None)
    parser.add_argument("-o", "--output", default="src/leap/leap_builtin.c")
    # How the generated comment names the source. MSYS2 rewrites a POSIX path
    # argument for a native Python - /usr/share/zoneinfo/... arrives as
    # C:/msys64/usr/share/zoneinfo/... - so the path this script opened is not
    # the spelling the committed file records, and check-generated would call
    # an unchanged table stale. The Makefile passes the POSIX spelling here.
    parser.add_argument("--source-name", default=None)
    args = parser.parse_args()

    source = args.source
    if source is not None:
        if not os.path.exists(source):
            raise SystemExit("no such file: %s" % source)
    else:
        for candidate in DEFAULT_SOURCES:
            if candidate and os.path.exists(candidate):
                source = candidate
                break
        if source is None:
            raise SystemExit(
                "no leap-seconds.list found. Looked in: %s\n"
                "Pass one explicitly, or fetch it from\n"
                "  https://data.iana.org/time-zones/tzdb/leap-seconds.list"
                % ", ".join(c for c in DEFAULT_SOURCES if c))

    text = pathlib.Path(source).read_text(encoding="utf-8", errors="replace")
    entries, updated, expiry = parse(text)

    output = pathlib.Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    # LF line endings: the file is committed and compared byte for byte, and a
    # native Python on Windows would otherwise write CRLF.
    output.write_text(render(entries, updated, expiry, args.source_name or source),
                      newline="\n")

    print("%s: %d entries, expires %s"
          % (args.output, len(entries), iso(expiry)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
